### ISSUE TITLE
TestWriteLineLoadString Failed xUnitTest on PPC/mono 2.10.8.1

### ISSUE THREAD

**Issue by archanox** [soywiz-archive/SafeILGenerator#2]
'''
SafeILGenerator.Tests.Ast.Generators.GeneratorILTest.TestWriteLineLoadString : Assert.Equal() Failure
Position: First difference is at position 12
Expected: Hello World!
          Goodbye World!

Actual:   Hello World!
          Goodbye World!

Stack Trace:
  at SafeILGenerator.Tests.Ast.Generators.GeneratorILTest.TestWriteLineLoadString () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Output:
  {
      Console.WriteLine(@ARG(0));
      Console.WriteLine("Goodbye World!");
      return;
  }

```
ldarg.0 
call Void WriteLine(System.String)
ldstr Goodbye World!
call Void WriteLine(System.String)
ret
```

'''

**Comment by archanox** [comment]
I don't think this output (at least viewed on the mobile) is completely accurate.

There's an indentation problem on second line of the actual output string. It doesn't align with the second line of the expected string.

**Comment by soywiz** [comment]
Maybe on unix systems WriteLine outputs \n instead of \r\n. I think that there is a constant that contains the line ending for that system, but I dont remember what

**Comment by archanox** [comment]
Environment.NewLine

I'll test this hopefully soon.

**Comment by soywiz** [comment]
Yeah, that's the static field. In the test you can change "\n" by "" + Environment.NewLine + "" or maybe just using Console.Write or something like that.

**Comment by archanox** [comment]
This is resolved on a x64 VM. I'll reopen this issue if the TestWriteLineLoadString test fails on PPC.

**Comment by archanox** [comment]
Confirmed to pass all tests on PPC.
